apiVersion: apps/v1
kind: Deployment 
metadata: #Dictionary
  name: nginx
spec: # Dictionary
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      run: nginx
  template:  
    metadata: # Dictionary
      name: nginx
      labels: # Dictionary
        app: nginx
        run: nginx
        # Key value paids
    spec:
      containers: # List
        - name: nginx
          image: nginx
          ports: 
            - containerPort: 80 